### ISSUE TITLE
from finnlp.data_sources.news.finnhub import Finnhub_News

### ISSUE THREAD

**Issue by wangyeye66** [AI4Finance-Foundation/FinNLP#2]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[17], line 9
      7 from tqdm.notebook import tqdm
      8 # from meta.data_processors.yahoofinance import Yahoofinance
----> 9 from finnlp.data_sources.news.finnhub import Finnhub_News
     10 from finnlp.large_language_models.openai.openai_chat_agent import Openai_Chat_Agent

ModuleNotFoundError: No module named 'finnlp.data_sources.news.finnhub'

**Comment by oliverwang15** [comment]
Hi, Thanks for that bug report. I have just updated the [related notebook](https://github.com/AI4Finance-Foundation/FinGPT/blob/master/demos/chatgpt-robo-advisor-v1/ChatGPT_Robo_Advisor.ipynb) and you may always find the newest demos of how to use FinNLP [here](https://ai4finance-foundation.github.io/FinNLP/).

**Comment by wangyeye66** [comment]
Thank you
